### ISSUE TITLE
Problems logging out

### ISSUE THREAD

**Issue by keith24** [Tracman-org/Server#1]
When users log out, everything freezes.  Console logs: 
```
{ [NotFoundError: Not found error] name: 'NotFoundError', message: 'Not found error' }
http.js:690
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/home/keith/sites/tracman/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/keith/sites/tracman/node_modules/express/lib/response.js:163:12)
    at done (/home/keith/sites/tracman/node_modules/express/lib/response.js:957:10)
    at /home/keith/sites/tracman/node_modules/nunjucks/src/environment.js:22:23
    at RawTask.call (/home/keith/sites/tracman/node_modules/asap/asap.js:40:19)
    at flush (/home/keith/sites/tracman/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:448:13)
```
Don't worry, loyal users!  I'm on it!

**Comment by keith24** [comment]
Seems to be caused by the [error handler](https://github.com/Tracman-org/Server/blob/master/server.js#L74) sending a second response.  Looking for the first...
