### ISSUE TITLE
500 Error after linking Facebook

### ISSUE THREAD

**Issue by keith24** [Tracman-org/Server#78]
Linking is successful, but shows 500 with stack: 

```
❌ Error
    at Strategy.parseErrorResponse (/srv/tracman/node_modules/passport-facebook/lib/strategy.js:196:12)
    at Strategy.OAuth2Strategy._createOAuthError (/srv/tracman/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /srv/tracman/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /srv/tracman/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/srv/tracman/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/srv/tracman/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by keith24** [comment]
Can't reproduce
