### ISSUE TITLE
Fix Google login

### ISSUE THREAD

**Issue by keith24** [Tracman-org/Server#94]
```
May 15 17:24:01 khp nodejs[30239]: ❌ Error
May 15 17:24:01 khp nodejs[30239]:     at Strategy.OAuth2Strategy.parseErrorResponse (/srv/tracman/node_modules/passport-oauth2/lib/strategy.js:329:12)
May 15 17:24:01 khp nodejs[30239]:     at Strategy.OAuth2Strategy._createOAuthError (/srv/tracman/node_modules/passport-oauth2/lib/strategy.js:376:16)
May 15 17:24:01 khp nodejs[30239]:     at /srv/tracman/node_modules/passport-oauth2/lib/strategy.js:166:45
May 15 17:24:01 khp nodejs[30239]:     at /srv/tracman/node_modules/oauth/lib/oauth2.js:191:18
May 15 17:24:01 khp nodejs[30239]:     at passBackControl (/srv/tracman/node_modules/oauth/lib/oauth2.js:132:9)
May 15 17:24:01 khp nodejs[30239]:     at IncomingMessage.<anonymous> (/srv/tracman/node_modules/oauth/lib/oauth2.js:157:7)
May 15 17:24:01 khp nodejs[30239]:     at emitNone (events.js:91:20)
May 15 17:24:01 khp nodejs[30239]:     at IncomingMessage.emit (events.js:188:7)
May 15 17:24:01 khp nodejs[30239]:     at endReadableNT (_stream_readable.js:975:12)
May 15 17:24:01 khp nodejs[30239]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
May 15 17:24:01 khp nodejs[30239]:     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by keith24** [comment]
I don't know why... but this seems to have stopped since e5e68db.

**Comment by keith24** [comment]
It's only happening in production

**Comment by keith24** [comment]
Fixed for good: I'd had a mismatch in the configuration.
